### ISSUE TITLE
ctlrender is missing exr file format support because HAVE_OPENEXR is not defined

### ISSUE THREAD

**Issue by michaeldsmith** [ampas/CTL#108]
in the pull request #105 that was recently merged, the cmake refactor left out definition of `HAVE_OPENEXR` which is needed to compile `ctlrender `with EXR file format support.  

The definition of `HAVE_OPENEXR` was previously included in the `ctlrender` `CMakeLists.txt` file.  `HAVE_OPENEXR` should be defined if OpenEXR is found

`ctlrender` unit test currently only tests support for DPX and TIF files, the `ctlrender` unit test should be extended to test support for EXR files.

**Comment by michaeldsmith** [comment]
When investigating this issue, I found that processing an EXR with ctlrender causes a runtime check to fail with Visual Studio 2019:

\CTL\lib\IlmCtl\CtlTypeStorage.cpp - Line 661

'Run-Time Check Failure - The variable 'empty' is being used without being initialized'

**Comment by michaeldsmith** [comment]
to fix the run-time check, that occurs on line 661 of CtlTypeStorage.cpp,

change

`va_list empty;`

to 
`
va_list empty = {};`

**Comment by ThomasWilshaw** [comment]
I just tried to build CTL on Windows with EXR support and followed the suggestions here. As soon as I added `HAVE_OPENEXR` I got errors in `exr_file.cc`. Specifically that `std::ifstream ins;` was not initilised. I fixed this by adding `#include <fstream>` to the file and it all seems to work fine now.

Thanks for the recent changes btw, building in Visual Studio was a dream

**Comment by michaeldsmith** [comment]
thanks @ThomasWilshaw - I'll include your fix in the pull request I'm working on now to address this issue.

While working on fixing this issue, I added new valgrind tests that found some errors with ctlrender when using 16-bit EXR output, I made a new issue for the valgrind errors #109 

My plan is to merge the missing ctlrender EXR support fix first and then work on the valgrind errors that have been found.

**Comment by ThomasWilshaw** [comment]
Glad to help. Weirdly I'm also finding CTL is just not writing EXRs at all. I get the following output but no image is created:
```
ctlrender.exe -verbose  -ctl "E:\argentina_tests\xt2gamma_tests\ctl\xt2gamma.ctl" lattice.exr out.exr
global ctl parameters:

       source file: lattice.exr
  destination file: out.exr
destination format: exr
       input scale: default
      output scale: default
```

Any ideas?

**Comment by ThomasWilshaw** [comment]
NVM, I'm on Windows and it turns out you have to have a `main` function in your `ctl` file. There's even some comments about it here `transform.cc:346`

**Comment by michaeldsmith** [comment]
OK good to hear that the issue is resolved.  We should look at documenting the convention that requires main() function in CTL file, or at least printing some message when a main() function isn't found but is expected.

**Comment by ThomasWilshaw** [comment]
I think I managed to fix it. A CTL file must contain either a main function or a function with the same name as the file. The way this is implemented in ctlrender is whatever is after the last `/` in the file path of the ctl file is looked for as a function name. This breaks on Windows as Windows uses backslashes. I fixed it with a little `#ifdef WIN32` which I can submit if you want?

**Comment by michaeldsmith** [comment]
@ThomasWilshaw yes it would be great if you could submit a pull request that fixes that issue.  Describing the issue and fix within a new github issue would also be helpful.
