### ISSUE TITLE
Not having a main() function causes a crash on Windows

### ISSUE THREAD

**Issue by ThomasWilshaw** [ampas/CTL#111]
According to the CTL spec. all CTL files must contain either a `main()` function or a function with the same name as the source file. However in Windows only the `main()` function approach works as the way this is implemented in `ctlrender` is whatever is after the last `/` in the file path of the ctl file is looked for as a function name. This breaks on Windows as Windows uses `\` rather than `/`. This is even mentioned in a comment in `transform.cc`.

My proposed solution is to use `#ifdef WIN32` to look for backslashes rather than forward slashes in `transform.cc:346`. I'll also have a look at adding a test for this but I'm not sure how far I'll get with that as I've never used this test suite before.

**Comment by michaeldsmith** [comment]
Can you try adding a test for this so it could be run with Ctest ?  

I think you just need to add something like this to \CTL\unittest\ctlrender\CMakeLists.txt

`add_test(NAME "ctlrender-ctl-function-name-is-filename" COMMAND ctlrender -force -ctl functionname_is_filename.ctl bars_photoshop.exr out.exr)`

and then add the CTL file `functionname_is_filename.ctl` to the folder \CTL\unittest\ctlrender\
