### ISSUE TITLE
CTL cmake does not find required dependencies when using apt-get install libilmbase-dev libopenexr-dev

### ISSUE THREAD

**Issue by michaeldsmith** [ampas/CTL#117]
The recent PR #115 has significantly simplified the CTL build system, this is a great improvement.  But unfortunately, now CTL cmake can't find the required dependencies in Ubuntu when using the apt-get package manager to install libilmbase-dev and libopenexr-dev (`apt-get -y install libilmbase-dev libopenexr-dev`), which used to work before PR #115

one workaround that seems to resolve the issue is to change the following lines in `\CTL\CMakeLists.txt` from:

```
find_package(OpenEXR 3 CONFIG QUIET)
if(OpenEXR_FOUND)
  message(STATUS "Found OpenEXR ${OpenEXR_VERSION}")
else()
  find_package(OpenEXR 2 CONFIG REQUIRED)
endif()
```

to

```
find_package(OpenEXR 3 CONFIG QUIET)
if(OpenEXR_FOUND)
  message(STATUS "Found OpenEXR ${OpenEXR_VERSION}")
else()
  find_package(IlmBase REQUIRED)
  find_package(OpenEXR 2 REQUIRED)
endif()


```

**Comment by waebbl** [comment]
You could be right, and I had this line in my changes as well, at first. On my machine, OpenEXR-2.5.8 looks for IlmBase using a find_package or find_dependency call, so this wasn't needed and I dropped it. It shouldn't hurt to query for both packages anyway.
