### ISSUE TITLE
missing unit tests for code in directory /CTL/OpenEXR_CTL/exr_ctl_exr/

### ISSUE THREAD

**Issue by michaeldsmith** [ampas/CTL#129]
There are no unit tests for the code in this directory [/CTL/OpenEXR_CTL/exr_ctl_exr/](https://github.com/ampas/CTL/tree/master/OpenEXR_CTL/exr_ctl_exr/ )

**Comment by ThomasWilshaw** [comment]
I'm happy to look into this, what sort of tests are you looking for?

**Comment by michaeldsmith** [comment]
i think we could start with just a basic run of the `exr_ctl_exr` executable, similar to how the `ctlrender `units tests work
