### ISSUE TITLE
"Bad magic number" error on known valid OpenEXR files

### ISSUE THREAD

**Issue by scottdyer** [ampas/CTL#140]
Finally managed to get ctlrender to run without an iexDebug error, but now am getting an old error where valid OpenEXR files are not recognized and so no image processing takes place.

To be fair, this might be related to an old version of ctlrender since I had to resort back to the old brew formula install for it to run. Is there a way to check version on ctlrender?

`% ctlrender -ctl ~/aces-dev/transforms/ctl/utilities/ACESutil.Unity.ctl SonyF35.StillLife.exr ~/tmp/testout.exr `
> Unable to read tiff file: Not a TIFF or MDI file, bad magic number 12150 (0x2f76)unable to read file SonyF35.StillLife.exr (unknown format).

I now recall this error is perhaps why I went back and tried to reinstall everything from source, but then of course I was getting the iexDebugtrap error. 

Any recommendations on how to get rid of whatever linked files are causing the install from source to not work? Or, how I might get around this error when using the install from homebrew?

**Comment by michaeldsmith** [comment]
@scottdyer I think you can use homebrew to build/install from the master source branch by adding the `--head` argument, like this

`brew install --head ctl`

I will look into adding automatic version info to the ctlrender usage, that's a great idea.  

Let me know if build/install using `--head` fixes this error.

**Comment by michaeldsmith** [comment]
I confirmed that your test command/file using ctlrender installed with `brew install ctl` gives the error you reported "Unable to read tiff file..." and installing ctlrender install with `brew install --head ctl` fixes the issue.

**Comment by scottdyer** [comment]
After clearing everything out again and reinstalling using `--head`, it worked! 
Thank you!

**Comment by aforsythe** [comment]
Should the current `head` be tagged as a release and the `homebrew` formula updated so `brew install ctl` works without the need to use `--head`?

**Comment by michaeldsmith** [comment]
@aforsythe I just published release tag `ctl-1.5.3`, do you know how to update the `homebrew` formula?

**Comment by michaeldsmith** [comment]
I found the ctl homebrew formula on github, it looks like it has already picked up the ctl-1.5.3 tag release

https://github.com/Homebrew/homebrew-core/commits/c7caed52b7f11772bc73fd1df2197717f9a41454/Formula/c/ctl.rb

**Comment by aforsythe** [comment]
Just installed from `homebrew` using `brew install ctl` and works great now.  Thanks!
