### ISSUE TITLE
make check requires sudo on OS X

### ISSUE THREAD

**Issue by aforsythe** [ampas/CTL#47]
Running make check without sudo on OS X creates exceptions in tests 1 and 3.  See issue #46 and https://gist.github.com/aforsythe/1e827a9b6f5f2ab2f2c0 for more details.

**Comment by scottdyer** [comment]
This issue has resurfaced and fortunately there was a solution to try. However, it would be nice to resolve this so it doesn't come up again. So, what do we think might be the appropriate fix here? 

@cbenhagen Is it possible to have a brew formula reset environment variables? If so, perhaps we just have it set `CTL_MODULE_PATH=` before install?

**Comment by cbenhagen** [comment]
@scottdyer i proposed a change in the homebrew formula that unsets $CTL_MODULE_PATH during install. But what about other platforms? Shouldn't this be fixed somewhere else? Maybe the current directory should always get searched first like discussed in https://github.com/ampas/CTL/issues/26.
