### ISSUE TITLE
CTL git does not compile on windows

### ISSUE THREAD

**Issue by ggarra13** [ampas/CTL#52]
The first problem is that the constructor with ... is not recognized by the compiler.  The problem appears on VC10, VC11 and VC12.

[  4%] Building CXX object lib/IlmCtl/CMakeFiles/IlmCtl.dir/CtlExc.cpp.obj
CtlExc.cpp
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(95) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor available

F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(99) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor available

F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(101) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(103) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(105) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(107) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(109) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(111) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(113) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(115) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(118) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.h(121) : error C2512: 'Ctl::CtlExc' : no appropriate default constructor availabl
e
F:\code\lib\ctl-git2\lib\IlmCtl\CtlExc.cpp(80) : error C3861: 'va_copy': identifier not found
NMAKE : fatal error U1077: 'c:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe' : return code '0x2'

**Comment by kearney401** [comment]
By any chance was this resolved? Getting the same issue

**Comment by michaeldsmith** [comment]
windows compile was fixed by #107 - please reopen or submit new issues if needed
