### ISSUE TITLE
CTL git does not compile on windows (part 2)

### ISSUE THREAD

**Issue by ggarra13** [ampas/CTL#53]
CtlInterpreter.cpp is missing several includes and uses the unportable lrand48() function.

Here are the includes I had to add to make it portable.
# ifdef _WIN32

```
#include \<io.h\>
#include \<stdio.h\>
#include \<stdlib.h\>
#include \<time.h\>
#define snprintf _snprintf
```
# else

```
#include \<unistd.h\>
```
# endif

**Comment by michaeldsmith** [comment]
windows compile was fixed by #107 - please reopen or submit new issues if needed
