### ISSUE TITLE
CTL git is missing function exports

### ISSUE THREAD

**Issue by ggarra13** [ampas/CTL#54]
For building a proper DLL on windows, it is necesary to export all classes and public functions.
That needs an .h file with exports like:
# if defined(OPENEXR_DLL)

```
#if defined(ILMCTL_EXPORTS)
        #define ILMCTL_EXPORT __declspec(dllexport)
    #define ILMCTL_EXPORT_CONST extern __declspec(dllexport)
#else
        #define ILMCTL_EXPORT __declspec(dllimport)
        #define ILMCTL_EXPORT_CONST extern __declspec(dllimport)
#endif
```
# else

```
#define ILMCTL_EXPORT
#define ILMCTL_EXPORT_CONST extern const
```
# endif

and then the classes defined like:

class ILMCTL_EXPORT RcObject
{
...
};

**Comment by michaeldsmith** [comment]
windows compile was fixed by #107 - please reopen or submit new issues if needed
