### ISSUE TITLE
CTL Brew formula is outdated

### ISSUE THREAD

**Issue by hm1992** [ampas/CTL#59]
Installed ctl brew formula (it installed the other required formulae).
```
dyld: Library not loaded: /usr/local/lib/libImath-2_1.11.dylib
  Referenced from: /usr/local/bin/ctlrender
  Reason: image not found
Trace/BPT trap: 5
```
The ctlrender binary seems to be linking against libImath-2_1.11.dylib whereas I have libImath-2_2.12.dylib. I wonder if anything needs rebuilding, or whether the brew script needs changing?

**Comment by scottdyer** [comment]
Try
> brew install ctl --build-from-source

**Comment by aforsythe** [comment]
Is this something that @cbenhagen might be able to help with?

**Comment by cbenhagen** [comment]
Actually I can't do this myself. Bottles are built by the brew-bot. For this I opened a new issue on homebrew. As scott pointed out you can rebuild it yourself until this gets fixed:
```
brew install ctl --build-from-source
```

**Comment by aforsythe** [comment]
@cbenhagen  Would it be bad form to do `export HOMEBREW_BUILD_FROM_SOURCE=1 ` in `ctl.rb`?

**Comment by cbenhagen** [comment]
Yes it would. The bottles have been rebuilt with this commit: https://github.com/Homebrew/homebrew/commit/afa1702df25cc31ccb94464fd39040a5c13669a0

**Comment by aforsythe** [comment]
@cbenhagen thanks for your help
