### ISSUE TITLE
scatteredDataToGrid() in detail

### ISSUE THREAD

**Issue by nhatphongtran** [ampas/CTL#63]
How does the scatteredDataToGrid() function create the source and destination grid? Does it sort the values properly before so there are no odd twists in the transform? 

Reason I'm asking is I'm trying to match one macbeth to another by sampling the 24 source and destination patches and overall the results look pretty close, however the blacks get really lifted and the red patch that was matching pretty closely before got very desaturated. Does the interpolation of the grid towards the extreme boundaries of the grid cause the issues? Am I missing a step?

Thanks very much for any input!

Nhat

**Comment by michaeldsmith** [comment]
github issues is not currently being used for general questions.  you can have a look at the scatteredDataToGrid() code in \lib\IlmCtlSimd\CtlSimdStdLibInterpolator.cpp
