### ISSUE TITLE
CTL with function not named after filename appears to segfault.

### ISSUE THREAD

**Issue by sobotka** [ampas/CTL#64]
Segfault when a file is named something other than the function within it. Happens on @scottdyer's dev branch, likely happens in master?

**Comment by aforsythe** [comment]
Troy

Which CTL file are you trying to run?  Can you provide an example ctlrender command that segfaults?

Alex

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by sobotka** [comment]
I tried a simple script using the unity.ctl code, but named testing.ctl.

**Comment by aforsythe** [comment]
Can you attach your testing.ctl file?

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by sobotka** [comment]
[testing.ctl.txt](https://github.com/ampas/CTL/files/503649/testing.ctl.txt)

Used OCIO to generate a 65 cube testing EXR via:

    ociolutimage --generate --cubesize 65 --maxwidth 4225 --output cube65.exr

Then:

    ./ctlrender -ctl ./testing.ctl ~/Develop/Builds/Files/cube65.exr -force ./out.exr
    Segmentation fault

**Comment by aforsythe** [comment]
Ctlrender executes a main function inside the module called. Replace void unity with void main and try to run it again.


[Δ]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>




>On Sep 30, 2016, at 12:18 PM, Troy James Sobotka <notifications@github.com<mailto:notifications@github.com>> wrote:


testing.ctl.txt<https://github.com/ampas/CTL/files/503649/testing.ctl.txt>

Used OCIO to generate a 65 cube testing EXR via:

ociolutimage --generate --cubesize 65 --maxwidth 4225 --output cube65.exr


Then:

./ctlrender -ctl ./testing.ctl ~/Develop/Builds/Files/cube65.exr -force ./out.exr
Segmentation fault

**Comment by sobotka** [comment]
Will close, but I still think that segfault should be squished.
