### ISSUE TITLE
Compilation error caused by including OpenEXR related header

### ISSUE THREAD

**Issue by jasjuang** [ampas/CTL#66]
I am not able to compile the code because whenever a OpenEXR related header is included it throws an error. For example,

``````
/home/jasjuang/CTL/lib/IlmCtl/CtlExc.h:66:24: fatal error: IexBaseExc.h: No such file or directory
``````

Then I realized in CtlExc.h it's simply doing 

``````
#include <IexBaseExc.h> 
``````

but if I change the code to 

``````
#include <OpenEXR/IexBaseExc.h> 
``````

it passes compilation for this part. There are other numerous OpenEXR related header that throws the same compilation error? Why isn't there a OpenEXR prefix for all the included header? If I install it with sudo apt-get install libilmbase-dev, the header will showup at /usr/include/OpenEXR/IexBaseExc.h, if I install it from source, it will show up in /usr/local/include/OpenEXR/IexBaseExc.h, so no matter what there will be a OpenEXR prefix in the path for the header.

**Comment by meshula** [comment]
Including as <IexBaseExc.h> is pretty conventional, for example, the Alembic codebase also follows this pattern. Installs and builds of OpenEXR definitely build to include/OpenEXR, but at the moment, users of OpenEXR need to use a -I option to referencing include/OpenEXR as appropriate. So the fix is probably to adjust the cmake scripts for CTL to reference that directory if that's how OpenEXR is installed.

**Comment by jasjuang** [comment]
I am building CTL from cmake instead of plain old g++ commandline. How to adjust the cmake scripts to reference the directory when there could be two possible locations like /usr/include/OpenEXR and /usr/local/include/OpenEXR?

**Comment by meshula** [comment]
The Alembic cmake scripts are configured with input variables -
````
	-DALEMBIC_PYILMBASE_PYIMATH_LIB="${LIB_ROOT}/lib/libPyImath.dylib" \
	-DILMBASE_ROOT="${LIB_ROOT}" \
	-DALEMBIC_PYILMBASE_ROOT="${LIB_ROOT}" \
````
where ${LIB_ROOT} would be /usr or /usr/local according to your set up.

The OpenEXR discovery in OpenImageIO to be reliable and easy to use:

https://github.com/OpenImageIO/oiio/blob/master/src/cmake/modules/FindOpenEXR.cmake

````
  -DOPENEXR_CUSTOM_INCLUDE_DIR:STRING=${LIB_ROOT}/include \
  -DOPENEXR_CUSTOM_LIB_DIR=${LIB_ROOT}/lib \
````

My Cmake is not quite good enough to understand if the CTL cmake files work in a similar way.

**Comment by jasjuang** [comment]
Where are the Alembic cmake scripts? I did a `grep -r ALEMBIC * ` and it shows nothing.

Are you suggesting that I should replace the FindOpenEXR.cmake in CTL into the one from OpenImageIO?

**Comment by meshula** [comment]
Alembic's cmake module discovery scripts are here: https://github.com/alembic/alembic/tree/master/cmake/Modules

I'm only suggesting that if the CTL OpenEXR module doesn't accept an argument to point to your OpenEXR location (my cmake is not good enough to read the current logic and know that), then, perhaps the CTL logic can be modified to do that. Alembic and OpenImageIO both have implementations that allow it, so I list them as examples of how other projects have solved the problem.

PS I'm not part of the CTL team, just someone with a suggestion.

**Comment by jasjuang** [comment]
Thanks for all the feedback and suggestions. I am struggling to get cmake to discover my OpenEXR location. I get it to compile temporarily by changing the CTL code to prefix all the OpenEXR related includes with `OpenEXR/`. Would love to see someone providing a elegant solution to this.

**Comment by michaeldsmith** [comment]
CTL's FindIlmBase.cmake and FindOpenEXR.cmake were replaced with OpenVDB's FindIlmBase.cmake and FindOpenEXR.cmake in #107, this fixed all known build issues on many platforms.  CTL's build and Cmake processes were recently simplified, modernized and improved in Dec 2022 and Jan 2023.  Please reopen a new issue if you have the same or new problems with these recent master branch commits.
